# Generated by Django 4.1.7 on 2023-05-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='infra_doc',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
    ]
