# Generated by Django 4.1.7 on 2023-05-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0002_infrastructure_infra_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='scheme_doc',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
    ]
