# Generated by Django 4.1.7 on 2023-05-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0003_scheme_scheme_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='infra_doc',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='scheme_doc',
        ),
    ]
